2024-11-12 17:59:46,566 -|- WARNING -|- Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "Z:\Urban\Module 12\tests_12_4.py", line 23, in test_run
    obj2 = Runners.Runner(2)
           ^^^^^^^^^^^^^^^^^
  File "Z:\Urban\Module 12\Runners.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-12 17:59:46,567 -|- WARNING -|- Неверная скорость для Runner
Traceback (most recent call last):
  File "Z:\Urban\Module 12\tests_12_4.py", line 13, in test_walk
    obj1 = Runners.Runner('Вася', -1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\Urban\Module 12\Runners.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
